"""
Secondary AI Decision Maker (Meta-Labeling) module for Multi-Symbol Prediction Engine.
Implements Marcos López de Prado's two-tier architecture:
1. Primary Model: Predicts market direction (Long (+1), Short (-1), or Flat (0)).
2. Secondary AI Decision Maker (Meta Model): Evaluates quantitative microstructure features
   when a trade signal occurs, predicting the probability that the trade will be a winning trade.
   Acts as an institutional risk manager, filtering out false signals in choppy markets.
"""
import os
import joblib
import pandas as pd
import numpy as np
from xgboost import XGBClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score
import config


class MetaEnsemble:
    """
    Two-tier Secondary AI Decision Maker ensemble combining:
    1. XGBoost Classifier (Gradient boosted decision trees for temporal & feature interaction)
    2. Random Forest Classifier (Bagged decision trees for structural regime classification as per technicals.txt)
    """
    def __init__(self, xgb_model, rf_model):
        self.xgb_model = xgb_model
        self.rf_model = rf_model

    def predict_proba(self, X):
        prob_xgb = self.xgb_model.predict_proba(X)
        prob_rf = self.rf_model.predict_proba(X)
        return (prob_xgb + prob_rf) / 2.0

    def predict(self, X):
        probs = self.predict_proba(X)
        return np.argmax(probs, axis=1)


def train_meta_model(df_labeled, feature_cols, oos_preds_df=None, target_col='target', symbol=None):
    """
    Train the Secondary AI Decision Maker on trade signals generated by the Primary Model.
    Target variable (meta_label): 1 if Primary Model signal == Actual Outcome (win), 0 otherwise.
    """
    # Resolve per-symbol model paths
    if symbol is not None:
        from config import get_model_paths, get_symbol_profile
        model_paths = get_model_paths(symbol)
        profile = get_symbol_profile(symbol)
        meta_model_path = model_paths['meta']
        oos_preds_path = model_paths['oos_preds']
        sym_display = profile['display_name']
    else:
        meta_model_path = config.META_MODEL_PATH
        oos_preds_path = config.OOS_PREDS_PATH
        sym_display = 'XAUUSD (Legacy)'
    
    print(f"\n==================================================")
    print(f"TRAINING SECONDARY AI DECISION MAKER — {sym_display}")
    print(f"==================================================")
    
    df_meta = df_labeled.dropna(subset=[target_col]).copy()
    
    if oos_preds_df is not None and not oos_preds_df.empty:
        print(f"[MetaLabeling] Aligning Primary Model Out-of-Sample predictions ({len(oos_preds_df)} bars)...")
        df_meta['primary_pred'] = 0.0
        df_meta['primary_prob'] = 0.0
        
        common_idx = df_meta.index.intersection(oos_preds_df.index)
        df_meta.loc[common_idx, 'primary_pred'] = oos_preds_df.loc[common_idx, 'pred']
        df_meta.loc[common_idx, 'primary_prob'] = oos_preds_df.loc[common_idx, 'prob']
    else:
        print(f"[MetaLabeling] OOS predictions not available. Loading saved primary ensemble model...")
        xgb_path = model_paths['xgb'] if symbol is not None else config.XGB_MODEL_PATH
        lgb_path = model_paths['lgb'] if symbol is not None else config.LGB_MODEL_PATH
        xgb_m = joblib.load(xgb_path)
        lgb_m = joblib.load(lgb_path)
        X_all = df_meta[feature_cols].values
        
        prob_xgb = xgb_m.predict_proba(X_all)
        prob_lgb = lgb_m.predict_proba(X_all)
        prob_avg = (prob_xgb + prob_lgb) / 2.0
        
        df_meta['primary_pred'] = np.argmax(prob_avg, axis=1) - 1.0
        df_meta['primary_prob'] = np.max(prob_avg, axis=1)
        
    # Filter only rows where primary model triggered an entry signal
    trade_signals = df_meta[(df_meta['primary_pred'] != 0.0) & (df_meta['primary_prob'] >= config.CONFIDENCE_THRESHOLD)].copy()
    
    if len(trade_signals) < 20:
        print(f"[Warning] Only {len(trade_signals)} trade signals found. Relaxing confidence filter for Meta training...")
        trade_signals = df_meta[df_meta['primary_pred'] != 0.0].copy()
        
    print(f"[MetaLabeling] Total Candidate Signals for Decision Maker evaluation: {len(trade_signals)}")
    
    def get_meta_label(row):
        pred = row['primary_pred']
        actual = row[target_col]
        macro_bias = row.get('macro_bias', 0.0)
        
        # Primary logic: Did the trade win?
        if pred == 1.0 and actual == 1.0:
            win = 1
        elif pred == -1.0 and actual == -1.0:
            win = 1
        else:
            win = 0
            
        # Smart Money Override: 
        # If AI predicts Long (+1) but Macro Bias is heavily Bearish (< -1.5), REJECT TRADE.
        if pred == 1.0 and macro_bias <= -1.5:
            return 0
        # If AI predicts Short (-1) but Macro Bias is heavily Bullish (> 1.5), REJECT TRADE.
        if pred == -1.0 and macro_bias >= 1.5:
            return 0
            
        return win
            
    trade_signals['meta_label'] = trade_signals.apply(get_meta_label, axis=1)

    if trade_signals.empty:
        print("[Warning] No candidate trade signals available for meta-model training. Creating a conservative fallback model.")
        fallback_model = XGBClassifier(
            n_estimators=50,
            max_depth=2,
            learning_rate=0.05,
            random_state=42,
            eval_metric='logloss'
        )
        fallback_model.fit(np.zeros((1, len(feature_cols))), np.array([0]))
        meta_model = MetaEnsemble(fallback_model, RandomForestClassifier(n_estimators=10, random_state=42))
        meta_model.rf_model.fit(np.zeros((1, len(feature_cols))), np.array([0]))
        joblib.dump(meta_model, meta_model_path)
        print(f"[Saved] Secondary AI Decision Maker fallback model -> {meta_model_path}")
        return meta_model

    pos_count = sum(trade_signals['meta_label'] == 1)
    neg_count = sum(trade_signals['meta_label'] == 0)
    print(f"[MetaLabeling] Signal Outcome Distribution:")
    print(f"  Good Trades (Win = 1):  {pos_count} ({pos_count/len(trade_signals)*100:.1f}%)")
    print(f"  Bad Trades (Loss = 0):  {neg_count} ({neg_count/len(trade_signals)*100:.1f}%)")

    scale_weight = neg_count / max(1, pos_count)

    X_meta = trade_signals[feature_cols].values
    y_meta = trade_signals['meta_label'].values
    
    # Chronological split (80% train, 20% test) to prevent lookahead bias in Meta evaluation
    split_idx = int(len(X_meta) * 0.8)
    X_train_m, X_test_m = X_meta[:split_idx], X_meta[split_idx:]
    y_train_m, y_test_m = y_meta[:split_idx], y_meta[split_idx:]
    
    xgb_meta = XGBClassifier(
        n_estimators=150,
        max_depth=3,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        scale_pos_weight=scale_weight,
        random_state=42,
        eval_metric='logloss'
    )
    rf_meta = RandomForestClassifier(
        n_estimators=150,
        max_depth=6,
        class_weight='balanced',
        random_state=42
    )
    
    xgb_meta.fit(X_train_m, y_train_m)
    rf_meta.fit(X_train_m, y_train_m)
    meta_model = MetaEnsemble(xgb_meta, rf_meta)
    
    # Evaluate out-of-sample performance on chronological test set
    if len(X_test_m) > 0:
        test_preds = meta_model.predict(X_test_m)
        test_acc = accuracy_score(y_test_m, test_preds)
        print(f"\n--- AI Decision Maker Test Performance (20% Out-of-Sample) ---")
        print(f"  Accuracy: {test_acc*100:.1f}%")
        labels = sorted(np.unique(np.concatenate([y_test_m, test_preds])))
        target_names = [f'Class {label}' for label in labels]
        if len(labels) == 1:
            target_names = ['Reject (0)'] if labels[0] == 0 else ['Approve (1)']
        print(classification_report(y_test_m, test_preds, labels=labels, target_names=target_names))
        
    # Re-train on all candidate trade signals before deployment
    xgb_meta.fit(X_meta, y_meta)
    rf_meta.fit(X_meta, y_meta)
    meta_model = MetaEnsemble(xgb_meta, rf_meta)
    joblib.dump(meta_model, meta_model_path)
    print(f"[Saved] Secondary AI Decision Maker model -> {meta_model_path}")
    
    # If OOS predictions DataFrame was passed, check if 'meta_prob' already exists from CV walk-forward
    if oos_preds_df is not None and not oos_preds_df.empty:
        if 'meta_prob' in oos_preds_df.columns:
            print(f"[MetaLabeling] OOS predictions already contain walk-forward 'meta_prob'. Preserving 0% lookahead predictions.")
        else:
            oos_preds_df['meta_prob'] = 1.0  # default 1.0 for flat bars
            common_signals = oos_preds_df.index.intersection(trade_signals.index)
            if len(common_signals) > 0:
                X_oos_signals = df_labeled.loc[common_signals, feature_cols].values
                meta_probs_oos = meta_model.predict_proba(X_oos_signals)[:, 1]
                oos_preds_df.loc[common_signals, 'meta_prob'] = meta_probs_oos
            joblib.dump(oos_preds_df, oos_preds_path)
            print(f"[MetaLabeling] Updated OOS predictions file with 'meta_prob' column.")
        
    return meta_model
